### ISSUE TITLE
Flow v0.54.0 support 

### ISSUE THREAD

**Issue by skrivle** [freddi301/flow-validator#3]
Hi,

First of all thanks for this library, it's great!

I'm trying to upgrade our project to flow v0.54.0, but I'm seeing some issues caused by this library. I already looked at it briefly, but it looks pretty daunting at first glance. 

Most of the issues seem to be about Promises and async stuff ...

Anyway, just wanted to give you a heads up. If I'm able to come up with a solution I'll definitely open a PR. Not sure when or if that will happen though :-) 

Thanks!

Jelle

**Comment by freddi301** [comment]
> it looks pretty daunting at first glance

To nth glance too, it needs a little bit of refactor.

Upgraded to flow v0.54.0 in [0.6.2](https://github.com/freddi301/flow-validator/releases/tag/v0.6.2)

**Comment by skrivle** [comment]
Sweet! Thanks for the quick response. Awesome work!

**Comment by freddi301** [comment]
;)
